version: '3'
services:

  java-runner:
    image: codewars/java-runner
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: ''
    command: bash

  python-runner:
    image: codewars/python-runner
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: ''
    command: bash

  systems-runner:
    image: codewars/systems-runner
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: ''
    command: bash

  dotnet-runner:
    image: codewars/dotnet-runner
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
      - ./templates:/runner/templates
    entrypoint: ''
    command: bash

  # LANGUAGE SPECIFIC HELPERS
  python:
    image: codewars/python-runner
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: 'node run -l python'

  java:
    image: codewars/java-runner
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: 'node run -l java'

  cpp:
    image: codewars/systems-runner
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
    entrypoint: 'node run -l cpp'

  csharp:
    image: codewars/dotnet-runner
    volumes:
      - ./lib:/runner/lib
      - ./frameworks:/runner/frameworks
      - ./templates:/runner/templates
    entrypoint: 'node run -l csharp'
